name: Security audit
on:
  pull_request:
    paths:
      - 'Cargo.toml'
      - '**/Cargo.toml'
  # Bors related branches
  push:
    branches:
    - master
    - staging
    - trying
  schedule:
    - cron: '0 0 * * *'

# Allow the action to post about found problems
permissions:
  issues: write

jobs:
  security_audit:
    name: Rustsec Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
