name: Rust CI
on:
  # Always test pull requests
  pull_request:
  # Bors related branches
  push:
    branches:
      - master
      - staging
      - trying
  # Test once per week: Monday at 00:00
  schedule:
    - cron: "0 0 * * 1"

env:
  CARGO_INCREMENTAL: 0
  # Debug infos are not really needed for CI and this keeps the cache smaller
  CARGO_PROFILE_DEV_DEBUG: 0
  RUSTFLAGS: -D warnings

jobs:
  clippy_check:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        rust: ["stable", "nightly"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Install/Update the Rust version"
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal --component clippy
          rustup default ${{ matrix.rust }}
          cargo --version
          rustc --version
      - uses: Swatinem/rust-cache@v1
      - name: clippy "No Default Features" (${{ matrix.os }} / ${{ matrix.rust }})
        run: cargo clippy --workspace --no-default-features --all-targets
      - name: clippy "Default" (${{ matrix.os }} / ${{ matrix.rust }})
        run: cargo clippy --workspace --all-targets
      - name: clippy "All Features" (${{ matrix.os }} / ${{ matrix.rust }})
        run: cargo clippy --workspace --all-features --all-targets

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: "Install/Update the Rust version"
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal --component rustfmt
          rustup default ${{ matrix.rust }}
          cargo --version
          rustc --version
      - name: Rustfmt Check (${{ matrix.rust }})
        run: cargo fmt --all -- --check

  build_and_test:
    name: Build and Test
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        # It is good to test more than the MSRV and stable since sometimes
        # breakage occurs in intermediate versions.
        # IMPORTANT: Synchronize the MSRV with the Cargo.toml values.
        rust: ["1.46", "1.50", "1.55", "stable", "beta", "nightly"]
        crate: ["serde_with", "serde_with_macros", "serde_with_test"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Install/Update the Rust version"
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal
          rustup default ${{ matrix.rust }}
          cargo --version
          rustc --version
      - uses: Swatinem/rust-cache@v1

      # Build the project
      - name: "Build (${{ matrix.os }} / ${{ matrix.rust }} / Crate ${{ matrix.crate }})"
        run: cargo build --all-features --all-targets --manifest-path=${{ matrix.crate }}/Cargo.toml

      # The tests are split into build and run steps, to see the time impact of each
      # cargo test --all-targets does NOT run doctests
      # since doctests are important this should not be added
      # https://github.com/rust-lang/cargo/issues/6669
      #
      # We need to specify the manifest path, such that cargo knows where to apply the `no-default-features`.
      # This is no longer necessary for Rust 1.51 or resolver="2"
      # https://doc.rust-lang.org/nightly/cargo/reference/features.html#resolver-version-2-command-line-flags
      - name: "Test Build (No Default Features / ${{ matrix.os }} / ${{ matrix.rust }} / Crate ${{ matrix.crate }})"
        run: cargo test --no-default-features --no-run --manifest-path=${{ matrix.crate }}/Cargo.toml
      - name: "Test Run (No Default Features / ${{ matrix.os }} / ${{ matrix.rust }} / Crate ${{ matrix.crate }})"
        run: cargo test --no-default-features --no-fail-fast --manifest-path=${{ matrix.crate }}/Cargo.toml
      - name: "Test Build (Default Features / ${{ matrix.os }} / ${{ matrix.rust }} / Crate ${{ matrix.crate }})"
        run: cargo test --no-run --manifest-path=${{ matrix.crate }}/Cargo.toml
      - name: "Test Run (Default Features / ${{ matrix.os }} / ${{ matrix.rust }} / Crate ${{ matrix.crate }})"
        run: cargo test --no-fail-fast --manifest-path=${{ matrix.crate }}/Cargo.toml
      - name: "Test Build (All Features / ${{ matrix.os }} / ${{ matrix.rust }} / Crate ${{ matrix.crate }})"
        run: cargo test --all-features  --no-run --manifest-path=${{ matrix.crate }}/Cargo.toml
      - name: "Test Run (All Features / ${{ matrix.os }} / ${{ matrix.rust }} / Crate ${{ matrix.crate }})"
        run: cargo test --all-features --no-default-features --no-fail-fast --manifest-path=${{ matrix.crate }}/Cargo.toml

      - name: Run cargo-tarpaulin
        if: matrix.rust == 'stable'  && matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --out Xml --workspace --all-features -- --test-threads=1
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'

  # Added to summarize the matrix (otherwise we would need to list every single
  # job in bors.toml)
  # https://forum.bors.tech/t/bors-with-github-workflows/426
  tests-result:
    name: Tests result
    if: always()
    needs:
      - rustfmt
      - clippy_check
      - build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a success
        if: "needs.rustfmt.result == 'success' && needs.clippy_check.result == 'success' && needs.build_and_test.result == 'success'"
        run: exit 0
      - name: Mark the job as a failure
        if: "!(needs.rustfmt.result == 'success' && needs.clippy_check.result == 'success' && needs.build_and_test.result == 'success')"
        run: exit 1
